[package]
name = "whisper-keys"
version = "2.0.0"
edition = "2021"


[dependencies]
anyhow = "1.0.75"
dialoguer = "0.11.0"
home = "0.5.5"
rdev = "0.5.3"
rodio = "0.17.1"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
